version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=tasking
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
